"""cascade added to transaction history fk reference

Revision ID: 45c1ce6fc754
Revises: 1a3b58935f0a
Create Date: 2024-12-16 10:39:28.133196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c1ce6fc754'
down_revision: Union[str, None] = '1a3b58935f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
