"""cascade behaviour added to fks in transactions history-v2

Revision ID: 6497ecd308ce
Revises: 45c1ce6fc754
Create Date: 2024-12-16 11:47:02.635831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6497ecd308ce'
down_revision: Union[str, None] = '45c1ce6fc754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'to_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('transactions_from_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_to_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['pk_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'accounts', ['from_account_id'], ['pk_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_to_account_id_fkey', 'transactions', 'accounts', ['to_account_id'], ['pk_id'])
    op.create_foreign_key('transactions_from_account_id_fkey', 'transactions', 'accounts', ['from_account_id'], ['pk_id'])
    op.alter_column('transactions', 'to_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'from_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
